### ISSUE TITLE
[Presentation] Project Purpose

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#111]
Answer the following points in the google docs (https://docs.google.com/document/d/1Hp1m2dzdOW72ORM08mTWqcpApCG7VYr1zI42JZevB2g/edit?usp=sharing):

1) Describe the motivation/purpose
2) What was the need for the system
3) How will it make money

These are all related to the project, view project presentation on moodle for more info.

**Comment by SalmaAl22** [comment]
Is this due today or Friday? Since it's not mentioned in the sprint grading rubric and we only need to submit the presentation powerpoint 24h before the presentation.
