### ISSUE TITLE
Manage users

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#14]
Admin should be able to manage users once this issue is resolved

**Comment by SalmaAl22** [comment]
Assessed at the beginning of SPRINT2

Associated Tasks:
-Create front end for removing a course from pending list.
-link the front-end with the back-end in so when When the user goes to change the  information, it must be updated in the backend. 

Difficulty:
5

Priority:
MED

Risk:
MED - This is to give the option of removing a user in the list . Not being able to remove a user is not important to the functioning of the entire site. However customization and error correction is important.

**Comment by wam82** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b781fa4c-7fff-8c1c-39a2-8725145c4ab0"><div dir="ltr" style="margin-left:0pt;" align="left">

Tested Requirement | See all students and employers profiles and delete one
-- | --
Quick Description | Once on the homepage after logging in: The admin must be able to see all students and employers account
Prerequisite | Database for user accounts connected, configured and deployed. Database for job applications connected, configured and deployed. Database for job postings connected, configured and deployed. The user must be an ‘ADMIN’ type account.
Input | A successful login with type of account ‘ADMIN’, press of remove button
Expected Output | Display all the students and employers account A remove button next to each employer and student. Once the button is pressed, user and all of its job postings should be delete as well as the applications to those job postings
Observed Output | All users are shown. When the button is pressed, all is deleted according to plan.
Verdict | Passed
Comments | The organization of the page differs from what originally planned but all the users appear

</div></b>
