### ISSUE TITLE
Tasks due

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#20]
Add Head Hunter User and description in the readme
Format readme - Louka
Add team roles (backend/frontend) to all team members in the readme -Kevin

**Comment by wam82** [comment]
Set up the wiki page for meeting minutes
Create folder for Sprint 1 - Razvan

**Comment by SalmaAl22** [comment]
formatted the readme file!

**Comment by SalmaAl22** [comment]
Created the MEETING MINUTE page on wiki and added the past two meeting minutes

**Comment by arcvelit** [comment]
Added Headhunter user to README.md, formatted README.md, and validated the "Team Roles" task. 
<Need more descriptions in README.md>

**Comment by arcvelit** [comment]
Created specific issues for the tasks enumerated above
