### ISSUE TITLE
Create 2 tables for the database

### ISSUE THREAD

**Issue by Razvan-Alexandru** [wam82/teamname-soen341project2023#37]
1. the users 
 - id
 - name
 - type of user
 - cv (if student)
 - description/info
 - extra stuff if needed
2. job postings
 - id
 - title
 - tag(s)
 - posting info
 - array of students that applied (hidden)

**Comment by arcvelit** [comment]
Update on this issue, exploring Supabase as our first solution. More to come when tables are done and DB is accessible.

**Comment by arcvelit** [comment]
Successfully created USERS database with data types.
As "extra stuff" there is an "info" field in which we can store json. Thoughts? @Razvan-Alexandru

**Comment by Razvan-Alexandru** [comment]
very good love it <3

**Comment by arcvelit** [comment]
Modified USERS table
![image](https://user-images.githubusercontent.com/86175300/221986233-9c5c6abb-3212-4157-bdef-f5aebbcc184e.png)
And created POSTINGS table
![image](https://user-images.githubusercontent.com/86175300/221986490-b6471871-cbec-4f6d-bc37-1ee7f9e14cdb.png)
@SalmaAl22 and @Amir8Abdullah anything we must add?

**Comment by SalmaAl22** [comment]
yes, sure everything looks great! :)

**Comment by arcvelit** [comment]
Cool! Closing and we will discuss the api in next sprint.
