### ISSUE TITLE
Parse through candidates

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#38]
User should be able to parse through different candidates using filters

**Comment by Amir8Abdullah** [comment]
User Story: As a headhunter, I want to be able to parse through different candidates using filters.

Associated Tasks:

Database for user accounts connected, configured and deployed.
Database for job postings connected, configured and deployed
Database for job applications connected, configured and deployed.
Implementation of filter handling full implemented.

Priority:
LOW - It is not a feature necessary for the functionality of a headhunter. Headhunter is still capable of parsing through all type of users without having filter.

Risk:
LOW - This requires to search through applicants who applied for the job which is handled in the backend. It does not pose any type of risk.

Countermeasure:
Handle the filter application in the backend.

**Comment by wam82** [comment]
This will not be implemented as the feature is to big for the amount of time remaining and the scope of the project
