### ISSUE TITLE
[TASK/Issue#6] Create account/register

### ISSUE THREAD

**Issue by SalmaAl22** [wam82/teamname-soen341project2023#53]
-Create a JavaScript file that creates the layout of page where a user can register for new account.
-create the CSS file that designs the registration page.

**Comment by SalmaAl22** [comment]
Completed the front-end design of the registration page. The work is located in the dev/registration/registrationPage. 
PS: 
-The button in the page aren't linked to anything and cannot take the user to other pages. 
-the users that are registering aren't having their information anywhere

**Comment by wam82** [comment]
Progress can be seen in pull request #52

**Comment by wam82** [comment]
Issue closed with pull request #52
