### ISSUE TITLE
Create Account/Register

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#6]
User should be able to create a new account once this issue is resolved.

**Comment by SalmaAl22** [comment]
![Capture](https://user-images.githubusercontent.com/77644406/221987826-f5dcea73-0f16-48db-b011-dadc5366b932.PNG)
Does it look good @arcvelit @Razvan-Alexandru

**Comment by arcvelit** [comment]
@SalmaAl22 in the database, users have "first_name" and "last_name"
Can we ask for those instead of "Full Name"? Thanks : - )

**Comment by SalmaAl22** [comment]
Sure, but can I push the work in sprint 3? :) @arcvelit

**Comment by arcvelit** [comment]
Sounds good, it's not urgent we'll link it to the backend by then!

**Comment by arcvelit** [comment]
We should create this issue shortly after end of Sprint 2 though

**Comment by wam82** [comment]
User Story: As a user, I want to be able to register a new account if I don't have any.

Associated Tasks:

- Create the register page where the user can input email address, password, first name, last name, and type of account in order to create a new account 
- Link the DB so that all fields are included and a new account is created

Story point:
5 - The register page has a few more fields to be implemented than the login page. However, the complexity of the backend is less than the one for the login as no operations are to be done.

Priority:
MED - Is a necessary feature for the final product but is less pressing than other activities

Risk:
MED - Is depended on by the login task
