### ISSUE TITLE
[TASK/Issue#8] Login (Backend)

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#60]
Create necessary DB tables such that a given email and password combination can be verified for authentication

Progress can be viewed in #8

**Comment by arcvelit** [comment]
Login backend was finalized with Abdullah during this evening's short meeting.
Should we close this, @Amir8Abdullah ?

**Comment by arcvelit** [comment]
Actually, please open it back if anything is needed.
