### ISSUE TITLE
[TASK/Issue#6] Link Database to newly created accounts 

### ISSUE THREAD

**Issue by SalmaAl22** [wam82/teamname-soen341project2023#63]
1. every time the register button is clicked, algorithm will run and check if inputted information are already found in database. 
2. if inputted data aren't in database, new field in the space will be created with the new information. if inputted data are in database, warning message will show on the registration page saying "profile already exist". 
3. the user would be taken to Profile page after button "register" is clicked if user is registered. the user would remain in the Register page after button "register" is clicked if his information is inputted email is already found in the database.

**Comment by SalmaAl22** [comment]
@Razvan-Alexandru is it good to split tasks into scenarios?

**Comment by wam82** [comment]
@arcvelit @Razvan-Alexandru Any updates for the backend regarding this task?
