### ISSUE TITLE
[TASK/Issue #14] Connect front and back end for the user profile

### ISSUE THREAD

**Issue by Amir8Abdullah** [wam82/teamname-soen341project2023#72]
When the user goes to change his information, it must be updated in the backend.

**Comment by KD54321** [comment]
As a user, I want to be able to update my info and profile picture and update send the information to the database in the backend so that I can save my new information if it ever happens to change.

Story points: 8

Risk: medium

**Comment by wam82** [comment]
@KD54321 Please view issue #12 for the user story, this is only a subtask of that user story.
