### ISSUE TITLE
Update registration page

### ISSUE THREAD

**Issue by Razvan-Alexandru** [wam82/teamname-soen341project2023#79]
@SalmaAl22 
- need to update the branch you're working on:
   - checkout to the epic branch epic/registration
   - git pull
   - checkout back to your dev branch and merge with the epic : git merge epic/registration
- check on github for any other modification that has been asked
- when you're done, push to github
-------
- integrate the backend by creating a new dev-branch and push the changes on the same epic branch
   - when this is done we can merge with the main branch

**Comment by SalmaAl22** [comment]
Given that there was short notice for the integration of backend with front end, it needs to be done in the next sprint as a separate issue. 
Also the whole website have been redesigned.
