### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by wam82** [wam82/teamname-soen341project2023#8]
User should be able to log into their existing account once this issue is resolved

**Comment by Razvan-Alexandru** [comment]
Front-end is finished.
Need to Link to database

**Comment by arcvelit** [comment]
Database is ready, we will communicate to link with the api backend.

**Comment by wam82** [comment]
User Story: As a student, I want to be able to log into the website and register a new account if I don't have any.

Associated Tasks:
- Create the log in page where the user can input email address and password to login (Issue #59) 
- Create necessary DB tables such that a given email and password combination can be verified for authentication (Issue #60)

Story point:
5 - The login page has fiew fields to be implemented the challenge comes in the backend when verifying the validity of an account for authentication

Priority:
MED - Is a feature necessary for the final product but is not depended on by any other features

Risk:
LOW - No other features depend on this in order to work

**Comment by wam82** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d52a21c1-7fff-7707-6dfc-6b3d2e7bf46f"><div dir="ltr" style="margin-left:0pt;" align="left">

Tested Requirement | Login into an account.
-- | --
Quick Description | Once on the login page: The user must provide email/username and password and press the login button to sign in.
Prerequisite | Database for user accounts connected, configured and deployed.  Login request handling frontend and backend fully implemented.
Input | Email/Username, password
Expected Output | The console on the frontend must print successful login along with the user type, email and a Boolean set to true. The console in the backend must print which body is being requested.
Observed Output | The console on the frontend prints successful login along with the user type, email and a Boolean set to true.The console in the backend prints which body is being requested.
Verdict | Passed
Comments | The login information for the user must be valid or it throws an error. The page must redirect to the homepage.

</div></b>
