### ISSUE TITLE
Implementation of a button that toggles darkmode on and off

### ISSUE THREAD

**Issue by SalmaAl22** [wam82/teamname-soen341project2023#80]
As a user, I want to be able to toggle between light mode and dark mode on the website by clicking a button so that I can adjust the interface to my preference and reduce eye strain when using the website in low light conditions.

**Comment by SalmaAl22** [comment]
User Story: As a user, I want to have the luxury to turn the website into dark mode whenever a toggle is on.

Associated Tasks:

- Create a toggle in the user profile.

- create an on handle function that would turn the whole website into dark mode once the toggle is switched to on.

Story point:
2- The implementation has few challenges as it is a straight forward front end implementation that does not require any back-end work. 

Priority:
LOW- It is not a feature necessary for the final product and is not depended on by any other features.

Risk:
LOW- there is few to no risk associate with these feature except some compatibility issues and user experience issues. it can also cause bugs if not thoughtfully tested. 

Countermeasure:
maximum amount of testing is necessary to guarantee that no bugs will happen. Also we got to make sure that the mode is compatible on most browser.

**Comment by wam82** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-7fc490de-7fff-e86b-04f6-c61fe115b4ee"><div dir="ltr" style="margin-left:0pt;" align="left">

Tested Requirement | Toggle Dark Mode
-- | --
Quick Description | Once logged in and in the home page, the user should press a button to turn the website into dark mode
Prerequisite | User is logged in
Input | Click on the Dark Mode button
Expected Output | The light sections of the website should turn dark
Observed Output | The light sections of the website turn dark
Verdict | Passed
Comments |  

</div></b>
